spring:
  application:
    name: cricket-app

  datasource:
    url: jdbc:mysql://localhost:3306/cricket?useSSL=false&serverTimezone=UTC
    username: myapp_user
    password: StrongPassword123!  ## Only for development, use environment variables or secrets management in production

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    baselineOnMigrate: false
    cleanDisabled: true
    locations: classpath:db/migration

logging:
  level:
    root: WARN
    com.gmh.cricket_app: INFO
    org.flywaydb: INFO
    org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

session:
  duration:
    ms: 86400000   # 24 hours

cricket:
  match:
    id-length: 12
  team:
    id-length: 8