ALTER TABLE "over"
  ADD COLUMN bowler_id VARCHAR(255),
  ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN total_runs INT NOT NULL DEFAULT 0,
  ADD COLUMN wickets INT NOT NULL DEFAULT 0;
