ALTER TABLE ball
  ADD COLUMN extra_runs INT NOT NULL DEFAULT 0,
  ADD COLUMN boundary_type VARCHAR(10),
  ADD COLUMN bowler_id VARCHAR(255);

ALTER TABLE "over"
  ADD COLUMN legal_ball_count INT NOT NULL DEFAULT 0;
